[package]
name = "pro"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.13.3"
handlebars = "4.3.7"
itertools = "0.11.0"
ron = "0.8.0"
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.103"
tiny_http = "0.12.0"
url = "2.4.0"
