[package]
name = "pro"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.13.3"
handlebars = "4.4.0"
itertools = "0.11.0"
ron = "0.8.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
tiny_http = "0.12.0"
url = "2.4.1"
